// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoqxOBBnXIDq3xGdxNj3vx_xcSA5tHMO0',
    appId: '1:1002255485744:web:23a85cc3e4135e4967d6f5',
    messagingSenderId: '1002255485744',
    projectId: 'habitsgo-d9937',
    authDomain: 'habitsgo-d9937.firebaseapp.com',
    storageBucket: 'habitsgo-d9937.appspot.com',
    measurementId: 'G-5MWGK4B0YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCraQfg18Gi5v3W-xEFcKdedtxfz43uzTA',
    appId: '1:1002255485744:android:65b4349a1d6eae6267d6f5',
    messagingSenderId: '1002255485744',
    projectId: 'habitsgo-d9937',
    storageBucket: 'habitsgo-d9937.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCormldWznhBQ_fbIVKQvIbGjblmygOyJY',
    appId: '1:1002255485744:ios:ba946e77092eb1cb67d6f5',
    messagingSenderId: '1002255485744',
    projectId: 'habitsgo-d9937',
    storageBucket: 'habitsgo-d9937.appspot.com',
    iosClientId: '1002255485744-h8qm18f6dripslpo3sm4a3t8qrk2126u.apps.googleusercontent.com',
    iosBundleId: 'com.krom.goHabits',
  );

}